### ISSUE TITLE
This repo vs. EverlastingBugstopper/binary-install

### ISSUE THREAD

**Issue by zwass** [cloudflare/binary-install#19]
Is one of these intended to be the canonical version? I see the @EverlastingBugstopper is the version available on NPM (https://www.npmjs.com/package/binary-install).

If EverlastingBugstopper/binary-install is the main repo these days, where is the best place to file issues?

**Comment by EverlastingBugstopper** [comment]
Hey, I thought I would transfer this to Cloudflare after leaving, but it turns out that I need this at my new gig and cloudflare folks don't have the bandwidth to maintain! You can feel free to file issues on my repo

**Comment by zwass** [comment]
@EverlastingBugstopper thanks for the quick response! Issues seem to be disabled on your fork.

**Comment by EverlastingBugstopper** [comment]
should be there now!

**Comment by zwass** [comment]
I now see Issues in https://github.com/EverlastingBugstopper/binary-install. Thanks!
